-- Create indexes on foreign keys and frequently searched columns
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_PRODUCTS_SUPPLIER ON PRODUCTS(SUPPLIER_ID);
CREATE INDEX IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_DATE ON ORDERS(ORDER_DATE);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS(PRODUCT_ID);
CREATE INDEX IDX_CUSTOMERS_COUNTY ON CUSTOMERS(COUNTY);
CREATE INDEX IDX_CUSTOMERS_PHONE ON CUSTOMERS(PHONE);
CREATE INDEX IDX_SUPPLIERS_COUNTY ON SUPPLIERS(COUNTY);