-- PDB Setup and Connection Script
-- Author: Fatime
-- Date: December 2025

-- Open the PDB
ALTER PLUGGABLE DATABASE MON_25858_FATIME_AGRISUPPLY_DB OPEN;

-- Switch to the PDB
ALTER SESSION SET CONTAINER = MON_25858_FATIME_AGRISUPPLY_DB;

-- Verify connection
SELECT SYS_CONTEXT('USERENV', 'CON_NAME') as CURRENT_PDB,
       SYS_CONTEXT('USERENV', 'DB_NAME') as DATABASE_NAME
FROM DUAL;